### ISSUE TITLE
[nest-swagger 项目] swagger 能否支持更换主题

### ISSUE THREAD

**Issue by shenxiang11** [FE-star/Plan-2022#5]
swagger 默认主题其实挺难用的。
之前工作中，有遇到过 BE 同事，更换了主题，会更加好用下，不知道 nest 是否支持更换

![image](https://user-images.githubusercontent.com/17292115/178434813-2c468159-89a9-4957-9b93-db1f73e796da.png)

**Comment by miniflycn** [comment]
理论上，找个Theme，然后去读取服务器的：/api-json 对应的json文件生成就好。
