### ISSUE TITLE
[Data Processor] 俺也用 golang + gin 实现了下

### ISSUE THREAD

**Issue by shenxiang11** [FE-star/Plan-2022#8]
https://github.com/shenxiang11/data-processor

测了下请求 12 个 activity 的情况，性能还是 go 好～

ts nestjs
<img width="1792" alt="截屏2022-07-21 11 48 17" src="https://user-images.githubusercontent.com/17292115/180126643-b32bc746-6878-4d20-9a73-fa2e9ec31ac8.png">

go gin
<img width="1792" alt="截屏2022-07-21 11 56 58" src="https://user-images.githubusercontent.com/17292115/180126985-81fe852d-d0ff-45a5-841d-e256bbda7737.png">

**Comment by miniflycn** [comment]
肯定是go的性能好的。
