### ISSUE TITLE
为了避免暴露可直接根据Activity ID获取商品列表的接口，可以怎么设计，避免爬虫通过该接口爬去商品信息？

### ISSUE THREAD

**Issue by shenxiang11** [FE-star/Plan-2022#9]
使用不连续的 id 作为 Activity ID
比如 uuid、mongodb 默认主键的那种、掘金文章（https://juejin.cn/post/**7004662774638837768**）id这种，让爬虫猜不到下一个id是什么

还有别的答案吗？

**Comment by miniflycn** [comment]
解法是再做个packageID类似的东西，把多个activityID打包，然后再用UUID作为packageID的ID，这样让爬虫尽量别爬出来。
